language: node_js
node_js:
  - "8"
sudo: enabled
before_script:
  - npm run build
addons:
  sauce_connect: true
  apt:
    update: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 6ab2a2736505400d0b8ded4b6828e80de78d1bb7
  keep-history: true
  on:
    branch: gh-pages