language: node_js
node_js:
  - "8"
sudo: enabled
addons:
  sauce_connect: true
  apt:
    update: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: df8f77d867d40d02dc9092f0d126b8dffb5e46af
  keep-history: true
  on:
    branch: master