language: node_js
node_js:
- '8'
sudo: enabled
addons:
  ssh_known_hosts: 47.52.171.181
  sauce_connect: true
  apt:
    update: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
after_success:
- ssh -tt root@47.52.171.181 < run ./script/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_91ba39662c5e_key -iv $encrypted_91ba39662c5e_iv
  -in id_rsa.enc -out id_rsa -d
